version: "3.8"

services:
  api:
    build: ./backend
    ports:
      - "8000:80"
    volumes:
      - ./data:/data
      - ./backend/.env:/var/www/html/.env

  frontend:
    build: ./frontend
    ports:
      - "3000:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

volumes:
  data:
