version: "3.8"

services:
  api:
    volumes:
      # Mount entire backend directory (excluding vendor/, storage/framework, etc. via .dockerignore)
      - ./backend:/var/www/html
      # Override .env mount to avoid conflicts
      - ./backend/.env:/tmp/.env.host
      - ./data/database.sqlite:/var/www/html/database/database.sqlite

  frontend:
    volumes:
      # Mount entire frontend directory (excluding node_modules/, dist/, etc. via .dockerignore)
      - ./frontend:/app