version: "3.8"

services:
  api:
    volumes:
      - ./backend:/var/www/html
      - ./backend/.env:/tmp/.env.host
      - ./data/database.sqlite:/var/www/html/database/database.sqlite

  frontend:
    volumes:
      - ./frontend:/app
