version: "3.8"

services:
  api:
    build: ./backend
    ports:
      - "8000:80"

  frontend:
    build: ./frontend
    ports:
      - "3000:5173"
    environment:
      - NODE_ENV=development

volumes:
  data:
