version: "3.8"

services:
  api:
    volumes:
      - ./backend:/var/www/html
      - /var/www/html/vendor
      - ./data/database.sqlite:/var/www/html/database/database.sqlite

  frontend:
    volumes:
      - ./frontend:/app
      - /app/node_modules
